"use client";

import { useState } from "react";

type Stage = "signup" | "home" | "setup" | "created";
type Format = "Pick'em" | "Pick'em + Side Bets" | "Side Bets Only";
type Sport = "College Football" | "NFL" | "College + NFL";
type Scoring = "Winning Percentage" | "Total Wins" | "Confidence Points";

export default function CommissionerProductionSim() {
  const [stage, setStage] = useState<Stage>("signup");
  const [step, setStep] = useState(0);
  const [showPreview, setShowPreview] = useState(false);
  const [showFeatures, setShowFeatures] = useState(false);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [leagueName, setLeagueName] = useState("");
  const [leagueTier, setLeagueTier] = useState("11–24");
  const [format, setFormat] = useState<Format>("Pick'em + Side Bets");
  const [sport, setSport] = useState<Sport>("College + NFL");
  const [scoring, setScoring] = useState<Scoring>("Winning Percentage");
  const [weeklyPicks, setWeeklyPicks] = useState(5);
  const [dogEnabled, setDogEnabled] = useState(true);
  const [dogPicks, setDogPicks] = useState(1);

  const price = leagueTier === "1–10" ? 20 : leagueTier === "11–24" ? 40 : leagueTier === "25–39" ? 60 : 80;

  if (stage === "signup") {
    return <main className="prod-onboarding">
      <header className="prod-header"><div className="prod-header-inner"><div className="prod-brand"><img src="/football-pickem-wordmark.png" alt="Football Pick'em" /></div><div className="prod-header-actions"><button type="button" onClick={() => setShowFeatures(true)}>How it works</button><button type="button" className="preview" onClick={() => setShowPreview(true)}>Preview App</button></div></div></header>
      <section className="prod-auth-shell">
        <div className="prod-auth-intro"><span className="prod-kicker">FOOTBALL PICK'EM</span><h1>Your league, built your way.</h1><p>Weekly picks, dog picks, peer-to-peer side bets, matchup research and live GameTracker — all inside one league.</p><div className="prod-feature-strip"><span><b>Pick'em</b><small>Custom weekly cards</small></span><span><b>Side Bets</b><small>Pregame + live</small></span><span><b>GameTracker</b><small>Follow games live</small></span></div></div>
        <div className="prod-auth-card"><div className="prod-auth-copy"><span>NEW ACCOUNT</span><h2>Start your league.</h2><p>Create an account first. Then create a league or join one from an invite.</p></div><label className="prod-field"><span>Your name</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Your name" /></label><label className="prod-field"><span>Email</span><input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" type="email" /></label><label className="prod-field"><span>Password</span><input value={password} onChange={(e) => setPassword(e.target.value)} placeholder="6+ characters" type="password" /></label><button type="button" className="prod-primary full" disabled={!name.trim() || !email.trim() || password.length < 6} onClick={() => setStage("home")}>Create Account</button><button type="button" className="prod-text-action" onClick={() => setShowPreview(true)}>Want to see it first? Preview the app →</button></div>
      </section>
      {showFeatures && <div className="prod-overlay"><section className="prod-features-modal"><header><div><span className="prod-kicker">WHAT'S INCLUDED</span><h2>Everything your league needs.</h2></div><button type="button" onClick={() => setShowFeatures(false)}>×</button></header><div className="prod-feature-groups"><article><span>PLAY</span><h3>Weekly Pick'em</h3><p>3–15 regular picks, optional dog picks, confidence scoring and season standings.</p></article><article><span>CHALLENGE</span><h3>Side Bets</h3><p>Pregame and live offers with spreads, moneylines, totals and a shared ledger.</p></article><article className="wide"><span>RESEARCH + FOLLOW</span><h3>Matchup Preview & GameTracker</h3><p>Advanced stats before kickoff, then live score, field position, plays and box score once the game starts.</p></article></div></section></div>}
      {showPreview && <div className="prod-preview-overlay"><div className="prod-preview-bar"><div><strong>Member App Preview</strong><span>The real Pick'em member experience.</span></div><button type="button" onClick={() => setShowPreview(false)}>Close</button></div><div className="prod-preview-placeholder">Real app preview loading here.</div></div>}
    </main>;
  }

  if (stage === "home") {
    return <main className="prod-onboarding"><header className="prod-header"><div className="prod-header-inner"><div className="prod-brand"><img src="/football-pickem-wordmark.png" alt="Football Pick'em" /></div><div className="prod-header-actions"><button type="button" className="preview" onClick={() => setShowPreview(true)}>Preview App</button></div></div></header><section className="prod-home"><span className="prod-kicker">WELCOME{name ? ", " + name.toUpperCase() : ""}</span><h1>What do you want to do?</h1><p className="prod-home-lead">Create a league as commissioner or join one from an invite.</p><div className="prod-start-grid"><button type="button" className="prod-start-card primary" onClick={() => { setStep(0); setStage("setup"); }}><span>COMMISSIONER</span><strong>Create a League</strong><small>Choose the format, sport, scoring, dog picks and side bets.</small><b>Start setup →</b></button><div className="prod-start-card"><span>PLAYER</span><strong>Join a League</strong><small>Enter the invite code your commissioner sent you.</small><label className="prod-inline-code"><input placeholder="INVITE CODE" /><button type="button">Join</button></label></div></div></section>{showPreview && <div className="prod-preview-overlay"><div className="prod-preview-bar"><strong>Member App Preview</strong><button type="button" onClick={() => setShowPreview(false)}>Close</button></div><div className="prod-preview-placeholder">Real app preview loading here.</div></div>}</main>;
  }

  if (stage === "created") {
    return <main className="prod-onboarding"><header className="prod-header"><div className="prod-header-inner"><div className="prod-brand"><img src="/football-pickem-wordmark.png" alt="Football Pick'em" /></div></div></header><section className="prod-created"><span className="prod-created-check">✓</span><span className="prod-kicker">LEAGUE CREATED</span><h1>{leagueName || "Your League"}</h1><p>The production flow would now take the commissioner into the league hub and let them invite members.</p><div className="prod-invite"><span><small>INVITE CODE</small><strong>PLAY-26</strong></span><button type="button">Copy Invite Link</button></div><div className="prod-created-actions"><button type="button" className="prod-secondary" onClick={() => { setStep(6); setStage("setup"); }}>Edit League</button><button type="button" className="prod-primary" onClick={() => setStage("home")}>League Home</button></div></section></main>;
  }

  return <main className="prod-onboarding">
    <header className="prod-header"><div className="prod-header-inner"><div className="prod-brand"><img src="/football-pickem-wordmark.png" alt="Football Pick'em" /></div><div className="prod-header-actions"><button type="button" className="preview" onClick={() => setShowPreview(true)}>Preview App</button></div></div></header>
    <div className="prod-setup-shell">
      <aside className="prod-setup-nav"><span className="prod-kicker">CREATE LEAGUE</span><h2>{leagueName || "New League"}</h2><div className="prod-step-list">{["League","Format","Sport","Pick'em","Side Bets","Schedule","Review"].map((label,index)=><button type="button" key={label} className={index===step?"active":index<step?"done":""} onClick={()=>setStep(index)}><i>{index<step?"✓":index+1}</i><span>{label}</span></button>)}</div></aside>
      <section className="prod-setup-panel"><div className="prod-mobile-progress">Step {step+1} of 7</div>
        {step===0 && <><span className="prod-kicker">LEAGUE</span><h1>Start with the basics.</h1><p className="prod-lead">Name the league and choose the player tier. The commissioner pays one season price for everyone.</p><label className="prod-field"><span>League name</span><input value={leagueName} onChange={(e)=>setLeagueName(e.target.value)} placeholder="Saturday Legends" /></label><div className="prod-section"><div className="prod-section-head"><h3>League size</h3><strong>{"$"+price}</strong></div><div className="prod-choice-grid two">{["1–10","11–24","25–39","40+"].map((tier)=><button type="button" key={tier} className={"prod-choice "+(leagueTier===tier?"active":"")} onClick={()=>setLeagueTier(tier)}><span className="prod-choice-copy"><strong>{tier+" players"}</strong>{leagueTier===tier&&<small>{"$"+(tier==="1–10"?20:tier==="11–24"?40:tier==="25–39"?60:80)+" for the season"}</small>}</span></button>)}</div></div></>}
        {step===1 && <><span className="prod-kicker">FORMAT</span><h1>What kind of league is it?</h1><p className="prod-lead">Turn on only the parts your group wants.</p><div className="prod-choice-grid">{(["Pick'em","Pick'em + Side Bets","Side Bets Only"] as Format[]).map((value)=><button type="button" key={value} className={"prod-choice "+(format===value?"active":"")} onClick={()=>setFormat(value)}><span className="prod-choice-copy"><strong>{value}</strong>{format===value&&<small>{value==="Pick'em + Side Bets"?"The full league experience.":value==="Pick'em"?"Weekly cards and standings.":"Peer-to-peer challenges only."}</small>}</span></button>)}</div></>}
        {step===2 && <><span className="prod-kicker">SPORT</span><h1>Choose the football slate.</h1><p className="prod-lead">Football is the first supported sport.</p><div className="prod-choice-grid">{(["College Football","NFL","College + NFL"] as Sport[]).map((value)=><button type="button" key={value} className={"prod-choice "+(sport===value?"active":"")} onClick={()=>setSport(value)}><span className="prod-choice-copy"><strong>{value}</strong>{sport===value&&<small>{value==="College + NFL"?"Both boards are available in the league.":"Only "+value+" games appear."}</small>}</span></button>)}</div></>}
        {step===3 && <><span className="prod-kicker">PICK'EM</span><h1>Set the weekly game.</h1><p className="prod-lead">Choose the standings system, weekly card size and dog picks.</p><div className="prod-section"><h3>Standings</h3><div className="prod-choice-grid">{(["Winning Percentage","Total Wins","Confidence Points"] as Scoring[]).map((value)=><button type="button" key={value} className={"prod-choice "+(scoring===value?"active":"")} onClick={()=>setScoring(value)}><span className="prod-choice-copy"><strong>{value}</strong>{scoring===value&&<small>{value==="Confidence Points"?"Assign 1–"+weeklyPicks+" exactly once across the "+weeklyPicks+" weekly picks.":value==="Winning Percentage"?"Correct picks divided by graded picks.":"Each correct regular pick is one win."}</small>}</span></button>)}</div></div><div className="prod-section"><div className="prod-section-head"><h3>Regular picks per week</h3><strong>{weeklyPicks}</strong></div><input className="prod-range" type="range" min="3" max="15" value={weeklyPicks} onChange={(e)=>setWeeklyPicks(Number(e.target.value))} /></div><div className="prod-section"><button type="button" className="prod-toggle" onClick={()=>setDogEnabled(!dogEnabled)}><span><strong>Include dog picks</strong><small>Underdog moneyline pick that must win outright.</small></span><i className={dogEnabled?"on":""}><b /></i></button>{dogEnabled&&<div className="prod-dog-card"><div><span>DOG PICK</span><strong>Reward the upset call.</strong><p>A losing dog does not add a regular loss. Winning dogs earn +1, +2 or +3 based on how large the underdog is.</p></div><div className="prod-dog-tiers"><span><b>+7 to +9.5</b><strong>+1</strong></span><span><b>+10 to +19.5</b><strong>+2</strong></span><span><b>+20+</b><strong>+3</strong></span></div><small>{scoring==="Confidence Points"?"Dog bonuses are points.":"Dog bonuses are wins."}</small></div>}</div>{dogEnabled&&<div className="prod-section"><h3>Dog picks per week</h3><div className="prod-choice-grid three">{[1,2,3].map((count)=><button type="button" key={count} className={"prod-choice "+(dogPicks===count?"active":"")} onClick={()=>setDogPicks(count)}><strong>{count+(count===1?" dog":" dogs")}</strong></button>)}</div></div>}</>}
        {step===4 && <><span className="prod-kicker">SIDE BETS</span><h1>Choose how members can challenge each other.</h1><p className="prod-lead">Pregame and live spreads, moneylines and totals can be tracked inside the league without the app holding funds.</p><div className="prod-feature-groups"><article><span>PREGAME + LIVE</span><h3>Peer-to-peer offers</h3><p>Members send an offer directly to another league member and the app keeps the result in the ledger.</p></article><article><span>MARKETS</span><h3>Spread · ML · O/U</h3><p>Use the same market types already built into the current Side Bets experience.</p></article></div></>}
        {step===5 && <><span className="prod-kicker">SCHEDULE</span><h1>Choose when picks lock.</h1><p className="prod-lead">Use game-by-game kickoff locks or one universal weekly deadline.</p><div className="prod-choice-grid two"><button type="button" className="prod-choice active"><span className="prod-choice-copy"><strong>Each game at kickoff</strong><small>Future games remain editable after earlier games begin.</small></span></button><button type="button" className="prod-choice"><span className="prod-choice-copy"><strong>One weekly deadline</strong><small>Freeze the whole card at one commissioner-set time.</small></span></button></div></>}
        {step===6 && <><span className="prod-kicker">REVIEW</span><h1>Everything looks ready.</h1><p className="prod-lead">Review the league before checkout and invitations.</p><div className="prod-review"><div className="prod-review-head"><div><small>LEAGUE</small><strong>{leagueName||"Untitled League"}</strong><span>{name||"Commissioner"}</span></div><b>{"$"+price}</b></div><div className="prod-summary-row"><span>Players</span><strong>{leagueTier}</strong></div><div className="prod-summary-row"><span>Format</span><strong>{format}</strong></div><div className="prod-summary-row"><span>Football</span><strong>{sport}</strong></div><div className="prod-summary-row"><span>Scoring</span><strong>{scoring}</strong></div><div className="prod-summary-row"><span>Weekly card</span><strong>{weeklyPicks+" picks"+(dogEnabled?" + "+dogPicks+(dogPicks===1?" dog":" dogs"):"")}</strong></div></div><div className="prod-review-actions"><button type="button" className="prod-secondary" onClick={()=>setShowPreview(true)}>Preview App</button><button type="button" className="prod-primary" onClick={()=>setStage("created")}>Simulate Checkout & Create</button></div></>}
        <footer className="prod-setup-actions"><button type="button" className="prod-secondary" onClick={()=>step===0?setStage("home"):setStep(step-1)}>Back</button>{step<6&&<button type="button" className="prod-primary" onClick={()=>setStep(step+1)}>Continue</button>}</footer>
      </section>
    </div>
    {showPreview&&<div className="prod-preview-overlay"><div className="prod-preview-bar"><div><strong>Member App Preview</strong><span>The real Pick'em member experience.</span></div><button type="button" onClick={()=>setShowPreview(false)}>Close</button></div><div className="prod-preview-placeholder">Real app preview loading here.</div></div>}
  </main>;
}
